file_list = [
     "guardian.sql",
    # "bank_account.sql",
    # #"broadcast_childScope.sql", #MS
    # #"broadcast_classScope.sql", #MS
    # "child_childRelation_parent.sql",
    # "withdrawal.sql",
    # "child_absent_subsidy_log.sql",
    # "address.sql",
    # "accpac_posting_childScope.sql",
    # "accpac_posting_registrationChildScope.sql",
    # "attendance.sql",
    # "bankAccountAttribute_stateHistory.sql",
    # "billable_program_billing_child_arrangement.sql",
    # "blacklist_blDraft_blActivityLog.sql",
    # "centre_draft_address.sql",
    # "check_in_out.sql",
    # "checklist_report_migrated.sql",
    # "child_activity_log.sql",
    # "child_attribute.sql",
    # "child_audit_log.sql",
    # "child_authorised_personal.sql",
    # "child_balance_sheet.sql",
    # "child_balance_sheet_audit_log.sql",
    # "child_class.sql",
    # "child_credit_balance_track.sql",
    # "child_fee_tier.sql",
    # "child_financial_assistance.sql",
    # #"child_high_frequency_evaluation.sql", #MS?
    # "child_history.sql",
    # "child_level.sql",
    # "child_snapshot.sql",
    # "credit_debit_note_audit_log.sql",
    # "credit_debit_note_item.sql",
    # "custom_subsidy.sql",
    # "discount_arrangement.sql",
    # "failed_disbursement.sql",
    # "giro_transaction.sql",
    # "document_fkChild.sql", #failed
    # "document_fkRegistrationChild.sql", #failed
    # "document_fkRegistrtaionParent.sql", #failed
    # "document_withdrawalDraft.sql",
    # "document_transferDraft.sql",
    # "document_bankAccount.sql",
    # "lead.sql",
    # "lead_child.sql",
    # "lead_activity_log.sql",
    # "leave.sql",
    # "leave_audit_log.sql",
    # "leave_document.sql",
    # "leave.sql",
    # "invoice_fkChild.sql",
    # "invoice_audit_log.sql",
    # "invoice_item.sql",
    # "invoice_outstanding_trace.sql",
    # "invoice_void_note.sql",
    # "invoice_void_note_audit_log.sql",
    # "linkpoint_card_detail.sql",
    # "linkpoint_child_exception.sql",
    # "linkpoint_transaction.sql",
    # "linkpass_delete_log.sql",
    # "device.sql",
    # "marketing_consent_fkUser.sql",
    # "marketing_consent_fkMarketingConsentUser.sql",
    # "marketing_consent_audit_log.sql",
    # "marketing_consent_business_entity.sql",
    # #"notification.sql", # run later. very large dataset
    # #"notification_archive.sql", # run later. very large dataset
    # "guardian_centre_verification.sql",
    # "parent_attribute.sql",
    # "parent_snapshot.sql",
    # "paynow_transaction.sql",
    # "paynow_transaction_item.sql",
    # "receipt_fkChild.sql",
    # "receipt_fkRegistrationChild.sql",
    # "receipt_audit_log_fkChild.sql", #failed and waiting for Kai's feedback
    # "receipt_audit_log_fkRegistrationChild.sql", ##failed and waiting for Kai's feedback 
    # "refund.sql",
    # "registration_audit_migrated_log.sql",
    # "registration_child_activity_log.sql",
    # "registration_child_attribute.sql",
    # "registration_child_mapping.sql",
    # "registration_child_tag.sql",
    # "registration_family_member.sql",
    # "registration_state_history.sql",
    # "receipt_offset_payment_source_ch.sql",
    # "receipt_offset_payment_source_re.sql",
    # "soa_monthly_pdf.sql",
    # "statement_of_account.sql",
    # "subsidy_arrangement.sql",
    # "temporary_withdrawal.sql",
    # "temporary_withdrawal_draft.sql",
    # "trade_debt_notification_log.sql",
    # "transfer_transferd_transferdi.sql",
    # "transfer_draft_activity_log.sql",
    # "user.sql",
    # "user_access_control.sql",
    # "user_access_control_audit_log.sql",
    # "user_audit_log.sql",
    # "user_device.sql",
    # "user_role_relation.sql",
    # "user_role_relation_audit_log.sql",
    # "waitlist_tag.sql",
    # "withdrawal_draft_activity_log.sql"
]