file_list = [
     ########### cycle 1
     # "check_in_out.sql",
     # "child_health_record.sql",
     # "class_attendance.sql",
     # "class_activity_fkChild.sql",
     # "class_activity_fkClass.sql",
     ########### cycle 2
     # "checklist_report_migrated.sql",
     # "child_high_frequency_evaluation.sql",
     # "child_language_function_evaluation.sql",
     # "child_learning_goal_evaluation.sql",
     # "child_letter_identification_evaluation.sql",
     # "child_literacy_tracking_section_one_evaluation.sql",
     # "child_literacy_tracking_section_two_evaluation.sql",
     # "child_multi_literacy_evaluation.sql",
     # "child_reading_behavior_evaluation.sql",
     ########### cycle 3
     # "class_activity_comment.sql",
     # "class_activity_log.sql",
     # "class_activity_developmental_and_learning_area.sql",
     # "class_activity_migrated_fkChild.sql",
     # "class_activity_migrated_fkClass.sql",
     # "class_activity_learning_goal.sql",
     # "class_activity_lesson_plan.sql",
     # "class_activity_migrated_log.sql",
     # "class_activity_parent_interaction_fkChild.sql",
     # "class_activity_parent_interaction_fkClass.sql",
     # "class_activity_tag_relation.sql",
     ########### cycle 4
     # "portfolio.sql",
     # "portfolio_child_learning_goal_evaluation.sql",
     # "portfolio_class_activity.sql",
     # "portfolio_class_teacher.sql",
     # "survey.sql",
     # "event.sql",
     # "visitor_log.sql",
     ########### cycle 5
     "pim_centre.sql",
     "pim_category.sql",
     "pim_audit_log.sql",
     "pim_centre_category.sql",
     "pim_centre_category_role.sql",
     "pim_enquiry.sql",
     "pim_enquiry_attachment.sql",
     "pim_enquiry_role.sql",
     "pim_enquiry_sendbird.sql",
     "pim_user_sendbird.sql",
]