file_list = [
############ cycle 1
# "accpac_posting_childScope.sql",
# "accpac_posting_registrationChildScope.sql",
# "address.sql",
# "attendance.sql",
# "bank_account.sql",
# "bankAccountAttribute_stateHistory.sql",
# "billable_program_billing_child_arrangement.sql",
# "blacklist_blDraft_blActivityLog.sql",
#"broadcast_childScope.sql", # N/A AS PER KAI
#"broadcast_classScope.sql", # N/A AS PER KAI
# "centre_draft_address.sql",
# "child_absent_subsidy_log.sql",
# "bus_child.sql",
########### cycle 2
# "child_activity_log.sql",
# "child_attribute.sql",
# "child_audit_log.sql",
# "child_authorised_personal.sql",
# "child_balance_sheet_audit_log.sql",
# "child_balance_sheet.sql",
# "child_childRelation_parent.sql",
# "child_class.sql",
# "child_credit_balance_track.sql",
# "child_fee_tier.sql",
############# cycle 3
# "child_financial_assistance.sql",
# "child_health.sql",
# "child_history.sql",
# "child_level.sql",
# "child_snapshot.sql",
# "credit_debit_note_audit_log.sql",
# "credit_debit_note_item.sql",
# "credit_debit_note.sql",
# "custom_subsidy.sql",
# "device.sql",
############## cycle 4
# "discount_arrangement.sql",
# "failed_disbursement.sql",
# "form_fkWithdrawalDraft.sql",
# "form_transferDraft.sql",
# "form_childLevel.sql",
#  "form_registrationChild.sql",
# "form_participant_fkWithdrawalDraft.sql",
# "form_participant_fkTransferDraft.sql",
# "form_participant_fkChildLevel.sql",
# "form_participant_fkRegistrationChild.sql",
############## cycle 5
# "giro_transaction.sql",
# "guardian_centre_verification.sql",
# "guardian.sql",
# "invoice_audit_log.sql",
# "invoice_fkChild.sql",
# "invoice_item.sql",
# "invoice_outstanding_trace.sql",
# "invoice_void_note_audit_log.sql",
# "invoice_void_note.sql",
############## cycle 6
# "leave_audit_log.sql",
# "leave_document.sql",
# "leave.sql",
# "level.sql",
# "linkpass_delete_log.sql",
# "linkpoint_card_detail.sql",
# "linkpoint_child_exception.sql",
# "linkpoint_transaction.sql",
# "marketing_consent_audit_log.sql",
# "marketing_consent_business_entity.sql",
# "marketing_consent_fkMarketingConsentUser.sql",
# "marketing_consent_fkUser.sql",
############## cycle 7
# "parent_attribute.sql",
# "parent_snapshot.sql",
# "paynow_transaction_item.sql",
# "paynow_transaction.sql",
# "registration_audit_migrated_log.sql",
# "registration_child_activity_log.sql",
# "registration_child_attribute.sql",
# "registration_child_mapping.sql",
# "registration_child_tag.sql",
# "registration_family_member.sql",
# "registration_state_history.sql",
############## cycle 8
# "soa_monthly_pdf.sql",
# "statement_of_account.sql",
# "subsidy_arrangement.sql",
# "temporary_withdrawal_draft.sql",
# "temporary_withdrawal.sql",
# "trade_debt_notification_log.sql",
# "transfer_draft_activity_log.sql",
# "transfer_transferd_transferdi.sql",
# "user_access_control_audit_log.sql",
# "user_access_control.sql",
# "user_audit_log.sql",
# "user_device.sql",
# "user_role_relation_audit_log.sql",
# "user_role_relation.sql",
# "user.sql",
############### cycle 9
# "withdrawal_draft_activity_log.sql",
# "withdrawal.sql",
# "refund_child_balance_audit_log.sql",
# "registration_parent.sql",
# "registration_parent_attribute.sql",
# "registration_child_parent.sql",
# "document_bankAccount.sql",
# "document_fkChild.sql",
# "document_fkRegistrationChild.sql",
# "document_fkRegistrtaionParent.sql",
# "document_transferDraft.sql",
# "document_withdrawalDraft.sql",
############### cycle 10
# "lead_activity_log.sql",
# "lead_child.sql",
# "lead.sql",
# "waitlist_tag.sql",
############### cycle 11
"receipt_audit_log_fkChild.sql",
"receipt_audit_log_fkRegistrationChild.sql",
"receipt_fkChild.sql",
"receipt_fkRegistrationChild.sql",
"receipt_offset_payment_source_ch.sql",
"receipt_offset_payment_source_re.sql",
"refund.sql",
"refund_child_balance_fkChild.sql",
"refund_child_balance_fkRegistrationChild.sql",
############## cycle 12 large dataset
# "notification_archive.sql", # run later. very large dataset
# "notification.sql", # run later. very large dataset,
]