file_list = [
    ## cycle 1
    # "child_parent_child_relation.sql",
    # "address.sql",
    # "accPacPosting_childAccpac.sql",
    # "child_activity_log.sql",
    # "enrichment_child_invoice_item.sql",
    # "enrichment_child_invoice_void_note.sql",
    # "enrichment_child_invoice_void_note_item.sql",
    # "enrichment_child_payment_transaction.sql",
    # "enrichment_child_receipt.sql",
    # "enrichment_class_attendance_fkChild.sql",
    # "enrichment_class_child.sql",
    # ## cycle 2
    # "enrichment_class_child_document.sql",
    # "enrichment_credit_debit_note.sql",
    # "enrichment_credit_debit_note_item.sql",
    # "enrichment_manual_refund.sql",
    # "epPaymentCard_epPaymentCardRelation.sql",
    # "enrichment_refund.sql",
    # "enrichment_refund_item.sql",
    # "enrichment_withdrawal.sql",
    # "card_tokens.sql",
    # "parent_attribute.sql",
    # "parent_entry_mapping.sql",
    # ## cycle 3
    # "temporary_withdrawal.sql",
    # "temporary_withdrawal_draft.sql",
    # "user_access_control_audit_log.sql",
    # "user_role_relation_audit_log.sql",
    # "withdrawal_wihdrawalDraft_withdrawalDraftItem.sql",
    # "withdrawal_draft_activity_log.sql",
    # "child_attribute.sql",
    # "child_class.sql",
    # "child_entry_mapping.sql",
    # "child_level.sql",
    # "document_type.sql",
    ## CYCLE 4
    # "user.sql",
    # "user_access_control.sql",
    # "user_audit_log.sql",
    # "user_role_relation.sql",
    ## CYCLE 5
    "enrichment_class_attendance_fkClass.sql", #failed
]